services:
  - type: web
    name: arna-bot
    env: python
    rootDir: .
    buildCommand: pip install --upgrade pip setuptools wheel && pip install -r Backend/src/requirements.txt
    startCommand: uvicorn Backend.src.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13